### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [n311pc/Tareas-Curso-BioinfInvRepro#2]
Súper, muy bien :) Suerte con Trinity y sus tardanzas en correr. Ve pensando qué gráficas hacer en R.

**Comment by NellyJazminPC** [comment]
Gracias! .... o habrá otro programa que me recomiendes? Pense en Trinity pero igual la verdad no tengo nada de experiencia con los transcriptomas :computer: :sweat_smile:  Hasta ahora, puchandole-curioseandole,  solo se me ha trabado una vez jeje pero creo que fue por que la linea de comandos no tenía lógica.

**Comment by AliciaMstt** [comment]
Trinity es bueno, vale la pena la espera y aprenderle bien. Pero ve pensando en lo de las gráficas y prueba con datos de chocolate que encuentres por ahí.
