### ISSUE TITLE
comentarios avances 3

### ISSUE THREAD

**Issue by AliciaMstt** [n311pc/Tareas-Curso-BioinfInvRepro#3]
"S He puesto cuidado en solo asignar CPU2 (2 nucleos) y GB4 (4 de ram), con eso la computadora solo se tardara pero no se dañara ...o si? :S"

No se dañan nunca por falta de RAM, solo se traban y renuncian a la tarea. Está bien que lo hagas con menos archivos y que lo dejes preparado para los 8. Puedes poner eso en tu proyecto final.

**Comment by NellyJazminPC** [comment]
Va, gracias Alicia. Otra duda, después del ensamblaje en Trinity pensaba evaluar la calidad del ensamblaje con bowtie pero para usar R me podrías recomendar algun análisis?
